### PR TITLE
[WIP] addition of image for construction starts project

### PR DESCRIPTION
**Pull request by chritter**
Hello,
We would like to request the addition of our project image for the construction starts project to the Covid-19 platform. The image was previously tested and build on the internal cloud. 

Thank you.

### CODE REVIEW

**Comment by blairdrummond** [comment]
The image doesn't seem to be building?

**Comment by chritter** [comment]
@blairdrummond There was a problem with the GDAL built. @mihir-gajjar  is helping with the setup.

**Comment by justbert** [comment]
Looks good!

**Comment by chritter** [comment]
I cannot run the CI pipeline anymore as it requires permissions. Going to create a feature branch.

**Comment by chritter** [comment]
New feature branch via the PR https://github.com/StatCan/daaas-containers/pull/16

**Pull request closed without merging**
