### PR TITLE
feat: add frontier-counts base

### PR DESCRIPTION
**Pull request by blairdrummond**

### CODE REVIEW

**Review by ca-scribner — DISMISSED** [review]
lgtm, but does this even need to be a daaas container?

**Comment by blairdrummond** [comment]
It adds about a minute speedup in a short pipeline used in a demo :-)

It there's a way to have cached pip stuff via kfp I'd also be amenable to that.

*Note: not merging yet as I have to add a few other things first*

**Comment by ca-scribner** [comment]
I figured it was about speed.

There might be a way to cache in kfp, but this is probably the easiest
thing to do!

**Comment by ca-scribner** [comment]
Does this need another lgtm and merge, or are you keeping it in the PR?

**Comment by brendangadd** [comment]
Can we get an issue for this, link this PR to it as closing, and put the issue in the project board in its place?

**Pull request closed without merging**
