### PR TITLE
add dockerfile for crops satellite image pipeline project

### PR DESCRIPTION
**Pull request by StanHatko**
@blairdrummond Please review and add the crops pipeline docker file.

### CODE REVIEW

**Comment by StanHatko** [comment]
It seems the pull request attempts to check every single container in the image, not just crops-pipeline. This seems inefficient and will scale poorly if there are many more containers in the future. Should I do the pull request differently so it only checks crops-pipeline, or is that something that we don't need to worry about for now?

**Comment by blairdrummond** [comment]
It's fine for now, github actions are free. Maybe we can tune the CI to be good tenants though.

With the image scanning, can you do a multi-stage built onto a ubuntu image? I think the security issues will go away if you do that.

```Dockerfile
# Build argument for digest for base image, at time of writing points to continuum/miniconda3 v4.9.2
ARG VERSION=4.9.2
ARG DIGEST_SHA=7838d0ce65783b0d944c19d193e2e6232196bada9e5f3762dc7a9f07dc271179
FROM continuumio/miniconda3:${VERSION}@sha256:${DIGEST_SHA} as build

# Install the package as normal:
COPY environment.yml .
RUN conda env create -f environment.yml

# Install conda-pack:
RUN conda install -c conda-forge conda-pack

# Use conda-pack to create a standalone enviornment
# in /venv:
RUN conda-pack -n frontier-counts-1 -o /tmp/env.tar && \
  mkdir /venv && cd /venv && tar xf /tmp/env.tar && \
  rm /tmp/env.tar

# We've put venv in same path it'll be in final image,
# so now fix up paths:
RUN /venv/bin/conda-unpack


# The runtime-stage image; we can use Debian as the
# base image since the Conda env also includes Python
# for us.
# TODO: Tag these
ARG UBUNTU_VERSION=20.04
ARG UBUNTU_DIGEST_SHA=4dd97cefde62
FROM ubuntu:${UBUNTU_VERSION}@sha256:${UBUNTU_DIGEST_SHA} AS runtime

# Create non-root user for container
ARG USER=jovyan
ARG APP_HOME=/home/jovyan

RUN adduser --system --group $USER \
    && mkdir -p $APP_HOME \
    && chown -R $USER:$USER $APP_HOME


# Copy /venv from the previous stage:
COPY --from=build /venv ${APP_HOME}/src/venv
COPY . ${APP_HOME}/src
WORKDIR ${APP_HOME}/src

# Start container as non-root user
USER $USER

# ENV WEBAPP_BASE_URL=http://localhost:8000/

# When image is run, run the code with the environment
# activated:
SHELL ["/bin/bash", "-c"]
CMD source venv/bin/activate && \
        #    python main.py
        #    gunicorn main:app --env WEBAPP_BASE_URL=$WEBAPP_BASE_URL
           gunicorn main:app -b 0.0.0.0:8000

EXPOSE 8000
```

**Comment by blairdrummond** [comment]
@StanHatko is has passed scanning. Should I merge?

**Comment by StanHatko** [comment]
Yes.

**Review by blairdrummond — APPROVED** [review]
LGTM!

**Pull request merged**
