### PR TITLE
feat(security): Add Trivy

### PR DESCRIPTION
**Pull request by sylus**

### CODE REVIEW

**Comment by justbert** [comment]
Oho! I was confused but now I see it!

LGTM!

**Comment by sylus** [comment]
Just need to review one more time missed one thing :P @justbert

**Comment by justbert** [comment]
This is really cool!

**Comment by sylus** [comment]
Think u have to merge if can ^_^ and thx!

**Comment by justbert** [comment]
Says it's blocked. Wants a review from StatCan/daaas-workflows

**Comment by sylus** [comment]
Hmm odd should allow me, you, or Zach. Ill just ping @blairdrummond for now

**Comment by justbert** [comment]
I've been judged wanting by the system! :P

**Pull request merged**
