### PR TITLE
feat(matrix): add the build matrix

### PR DESCRIPTION
**Pull request by blairdrummond**

### CODE REVIEW

**Comment by blairdrummond** [comment]
@sylus , my workflow works fine (and is faster), it's just that almost all images have vulnerabilities lol.

Plus side though, is that the parallelism will let the other images make it through.

**Comment by blairdrummond** [comment]
@ca-scribner  Would you be able to look at this quickly? This will unblock a bunch of the other PRs, it lets containers which pass scanning through, even if other images fail

**Comment by ca-scribner** [comment]
I read through it, but I can't actually approve on this repo (has to be Will or Zach) so just wrote some notes...

* I like the direction this goes in
* since we're refactoring, can we combine build and push to a single yaml?  Push is just "build + a step", so we can make them the same and put the final `push` step under an if statement that checks if this is a merge vs a PR.  That would make intent clearer with (I think) no downside 
* I slightly prefer an explicit matrix list (eg: write out "santander, openaddresses, kenchustuff, ..." in a matrix in the workflow rather than use the list of directories), but I'm fine with either.  Takes a tiny bit more maintenance to maintain the list but also feels clearer in intent.  At a minimum, add comments in the header of the workflow yaml **especially in the readme.md** explaining what will happen in the CI.  That way nobody gets surprised.  
* Let's remove the santander pruning from this and make it a separate PR.  It makes a review clearer a and also makes it more intuitive what happened (nobody will ever see "add the build matrix" and think "that's where I'll find that santander removal")

An alternate to this build matrix approach would be the submitter of each directory also submits a CI yaml.  That would make more sense if we expect CI to be different depending on the submission, but so far it doesn't matter.

**Comment by blairdrummond** [comment]
since we're refactoring, can we combine build and push to a single yaml? Push is just "build + a step", so we can make them the same and put the final push step under an if statement that checks if this is a merge vs a PR. That would make intent clearer with (I think) no downside

:+1:  Looks like there is [a way to do that](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif). I can try to add that this weekend

    I slightly prefer an explicit matrix list (eg: write out "santander, openaddresses, kenchustuff, ..." in a matrix in the workflow rather than use the list of directories), but I'm fine with either. Takes a tiny bit more maintenance to maintain the list but also feels clearer in intent. At a minimum, add comments in the header of the workflow yaml especially in the readme.md explaining what will happen in the CI. That way nobody gets surprised.

Actually avoiding touching the workflow file is a HUGE plus, because it avoids CODEOWNERS issues. It's because of edits to the workflow file that neither you or I are able to merge things in this repo usually, so avoiding that is an advantage (even though I'd typically agree)

    Let's remove the santander pruning from this and make it a separate PR. It makes a review clearer a and also makes it more intuitive what happened (nobody will ever see "add the build matrix" and think "that's where I'll find that santander removal")

I think the santander code was removed from the CI a while ago, the reason I removed it here is because it breaks the CI because it doesn't use the same "Flat" folder structure. I think it'll be ok, too, since it'll be marked in the commit history where it was removed, so it'll be easy to find. (I do agree in principle though)

    An alternate to this build matrix approach would be the submitter of each directory also submits a CI yaml. That would make more sense if we expect CI to be different depending on the submission, but so far it doesn't matter.

Yeah I get the idea, but it runs into code-owners pains if they need to touch the workflow file

**Comment by ca-scribner** [comment]
on the matrix/explicit listing stuff yeah there's pluses and minuses to both so I'm cool with this

For santander, I'm happy with removing it I just say cherry pick that one commit out into a separate PR and rebase this on that.  The commit history will be destroyed since we'll squash anyway, and they're really completely separate issues (you didn't need to remove santander to update the CI, and you didn't need updated CI to be able to remove santander).  Agreed santander breaks the build but I don't think that makes it enough of a joint issue to bundle into this PR.  Especially since it's a 5 min change to make Santander removal it's own PR

**Comment by ca-scribner** [comment]
For merging the build/push CI, there's a bunch of examples for if syntax in the mlops repo like [here](https://github.com/StatCan/kubeflow-mlops/blob/842616d1e963999c0e8491f3cb40105c6eef3b46/.github/workflows/iowa-ci.yml#L38).  I think those ones were a bit more complicated because its harder to decide if something is a comment vs an issue, but you get the idea.  

If you need the if statement more than once or twice, I found it clearer to make a job specifically for that test, then using it as a dependency to other jobs so they consume its output, like

```
  some_test:
    runs-on: ubuntu-latest
    outputs:
      value_of_test: ${{ steps.my_test.outputs.boolean }}
      pr_number: ${{ steps.get_pr_number.outputs.pr_number }}
    steps:
      # If this doesn't fire, the result will be empty and thus evaluate to false
      - name: The test
        if: (boolean expression)
        id: my_test
        run: echo "::set-output name=boolean::true"
  git_context:
    runs-on: ubuntu-latest
    needs: [some_test]
    if: needs.some_test.outputs.value_of_test
```

This way you can just test on `value_of_test` rather than write the logic in multiple places and risk them getting out of sync

**Comment by blairdrummond** [comment]
Done!

**Comment by blairdrummond** [comment]
Maybe lets do the build+push thing as a separate PR? We could probably apply this to kubeflow containers too.

**Comment by ca-scribner** [comment]
Yeah sounds good to me

**Comment by blairdrummond** [comment]
@zachomedia I think either you or Will need to give this an "Approve" in order to be merged. Lmk if looks good!

**Comment by blairdrummond** [comment]
@yabiza this PR will unblock your Webscraping work. Just needs to be reviewed and merged, but it is in the sprint so hopefully will happen soon.

**Comment by blairdrummond** [comment]
@zachomedia One question, would it make sense for us to start putting user images in a "Subfolder", e.g.

`$ACR/users/$image` instead of at the "Top level"?

**Review by zachomedia — APPROVED** [review]
Approved

**Comment by blairdrummond** [comment]
@yabiza Merged!!! You should be able to build stuff here now. You too @JosephKuchar

**Pull request merged**
